mantlenetworkio/op-geth

core/state_transition.go, core/types/deposit_tx.go, core/types/transaction.go, core/types/transaction_marshalling.go, internal/ethapi/api.go
Core change:
1. add `ethValue` in depositTx  and update the derive function for DepositTx
2. add `BVM_ETH` mint action on  `state_transition.go`
=> [R4R] {feature}: add BVM_ETH mint on op-geth

core/state_transition.go, core/txpool/txpool.go, core/types/meta_transaction.go, internal/ethapi/api.go, internal/ethapi/transaction_args.go
Core changes:
- when failing to check intrinsic gas, discard the transaction
- fix estimateGas when there are no gasPrice args in `TransactionArgs`
- add balance check when estimating meta transaction
=> [R4R]-[fee]feat: fix intrinsic gas check failed

internal/ethapi/transaction_args.go
Core change:
- use default gasPrice to set `gasPrice`, `gasFeeCap` and `gasTipCap` to avoid `maxPriorityFeePerGas` > `maxFeePerGas` when `estimateGas`
=> [R4R]-[fee]feat: fix estimateGas to avoid maxPriorityFeePerGas > maxFeePerGas

core/types/receipt.go, internal/ethapi/api.go
Core change:
- There are `DA*` values stored in legacy version ledger, and those transactions should be compatible for querying by `eth_getTransactionReceipt`
=> [R4R]-[transactionReceipt]feat: fix query legacy txs through transactionReceipt

core/state_transition.go, core/txpool/txpool.go, core/types/rollup_l1_cost.go
Core change:
- when setting tokenRatio, clear the `cacheBlockNum` and get the latest tokenRatio next time instead of using cache
=> [R4R]-[fee]feat: fix query tokenRatio

internal/ethapi/api.go
internal/ethapi: minor refactor in block serialization (#[27268](https://github.com/ethereum/go-ethereum/pull/27268))
=> R4R: optimize getBlockByNumber api

internal/ethapi/transaction_args.go
Core changes:
- use actual gasPrice to `estimateGas`, has 8 cases:
- 1 gasPrice is nil; GasTipCap is nil; GasFeeCap is nil
- use default gasPrice
- 2 gasPrice is nil; GasTipCap not nil; GasFeeCap is nil
- use default gasPrice
- 3 gasPrice is nil; GasTipCap is nil; GasFeeCap not nil
- use actual gasPrice
- 4 gasPrice is nil; GasTipCap not nil; GasFeeCap not nil
- use actual gasPrice
- 5 gasPrice not nil; GasTipCap is nil; GasFeeCap is nil
- use actual gasPrice
- 6 gasPrice not nil; GasTipCap not nil; GasFeeCap is nil
- wrong arguments
- 7 gasPrice not nil; GasTipCap is nil; GasFeeCap not nil
- wrong arguments
- 8 gasPrice not nil; GasTipCap not nil; GasFeeCap not nil
- wrong arguments
=> [R4R]-[op-geth]feat:use actual gasPrice to estimateGas

consensus/misc/eip1559.go, core/genesis.go, core/mantle_upgrade.go, core/mantle_upgrade_test.go, miner/worker.go, params/config.go
Core changes:
- use `block timestamp` as `BaseFee` upgrade flag
=> [R4R]-[baseFee]feat: use block time to determine baseFee upgrade

internal/ethapi/api.go
if metatx not nil, sponsorAmount is set by gasCap(price), but should be similar to gasPrice * gasUsed. this causes estimateGas failed if gasUsed larger than 1.(100percent and 0 fromBalance)
e.g.: 100% sponsor, and msg.sender has no MNT. sponsorAmount will be set as feeCap. Balance in total is 0 + feeCap, and will also set to "avaliable". Then allowance is set by avaliable div feeCap, so allowance will be 1. If only the gasUsed larger than 1, error msg "gas required exceeds allowance (1)" will be returned.
=> R4R: fix metatx estimateGas 

core/types/transaction.go
Core change:
- Tx Cost =  (gas * gasPrice) + (blobGas * blobGasPrice) + value
Releated PR:
- https://github.com/mantlenetworkio/op-geth/pull/35
=> [R4R]-[tx]fix: fix tx cost

.gitignore, common/types.go, core/state_transition.go, eth/tracers/api.go, graphql/graphql.go, internal/ethapi/api.go, internal/ethapi/api_test.go, internal/ethapi/transaction_args.go, params/config.go
EstimateGas performance optimization:
Reference：https://github.com/ethereum/go-ethereum/blob/master/eth/gasestimator/gasestimator.go#L52
1. Introduction of Optimistic Gas Limit
2. Finely Tuned Binary Search
3. Handling of Fee Caps
4. Rapid Processing of Special Cases
5. Joint Consideration of Account Balance and Gas Limits
6. Error Handling and Early Return
=> [R4R]-{estimateGas}feature: EstimateGas performance optimization

eth/api_backend.go, les/api_backend.go
In order to prevent normal users' transaction fees from being affected by network priority fees, and to keep the overall network transaction fee as low as possible, basefee is consistent, so cap is set to 0
=> R4R: feature/ivan:Set suggest tip cap to zero

core/error.go, core/state_transition.go, core/txpool/txpool.go, internal/ethapi/api.go, internal/ethapi/transaction_args.go, miner/worker.go
Core changes:
- discard invalid tx after `commitTransaction`, refer to [go-ethereum](https://github.com/ethereum/go-ethereum/pull/27038)
- fix the case gasPrice = 0 when `estimateGas`
- `gasLimit` should cover l1Cost when validating in txpool
- fix l1Cost when replacing tx in txpool, refer to [code](https://github.com/ethereum-optimism/op-geth/blob/336d284b606ec4792a605932201b97f04981db9d/core/txpool/legacypool/legacypool.go#L658)
=> [R4R]-[fee]fix: fix estimateGas; discard invalid tx

core/txpool/txpool.go, internal/ethapi/api.go, internal/ethapi/transaction_args.go
1. Removed an issue where gasPrice or gasFeeCap would default to baseFee when it was lower than baseFee, as this would cause estimateGas to succeed but eth_call to fail with the same parameters
2. When the user does not set the gasPrice or 1559 parameters, the from account balance should not be verified, otherwise the estimateGas will not be executed.
=> [R4R]-fix: eth_estimateGas

accounts/abi/bind/backends/simulated.go, internal/ethapi/api.go
When calling eth_estimateGas, if the EVM throws an error, it will result in the program throwing an "**_insufficient funds for gas * price + value_**" error instead of the correct EVM error.
**Cause:** When estimating gas in the layer 2, it includes gas cost from the layer 1. This causes a slight shortage when estimating gas using the user's entire balance. Additionally, during the re-estimation process, if an EVM error occurs but is not an out-of-gas error, it will be ignored. This ultimately leads to the entire estimation process failing to correctly throw an EVM error. Therefore, each estimation should include a check for an EVM result. If the result is not empty and not an out-of-gas error, the estimation should be terminated, and an exception should be thrown.
**Reproduction steps:** …
=> [R4R]-fix: estimate gas evm error

internal/ethapi/api.go
**Bug case:**
When calling across contracts, an opCall call error out of gas will occur. However, this error is not execution reverted, causing the error and cannot be captured by the call stack. Therefore, when subsequent opcode is executed, opRevert is triggered because the return value is not the expected value. But if this error is triggered during the bisection process, it can be tolerated because smaller gas is used in the estimation. 
**How to fix**
Therefore, the function of this flag is that as long as estimateGas is successful once during the bisection process, it will not terminate. The process of bisection and throwing an evm error (drawing on the idea of ​​Ethereum, using the largest balance to estimate once, if successful, no subsequent judgment errors will be made, if …
=> [R4R]-fix: contract call estimate gas bug

core/genesis.go, core/mantle_upgrade.go, core/state_transition.go, core/txpool/txpool.go, core/types/meta_transaction.go, core/types/meta_transaction_test.go, core/types/transaction_signing.go, internal/ethapi/api.go, internal/ethapi/transaction_args.go, light/txpool.go, params/config.go
Core changes:
1. ensure sponsor doesn't equal to tx sender
2. fix metatx estimateGas
3. fix metatx gas undercharge
4. optimize tx estimateGas check
=> R4R: metatx bugfix

core/genesis.go, core/mantle_upgrade.go, core/state_transition.go, params/config.go
Change the proxyAdmin owner address to `0x09734bB3980906Bb217305EA6Bd34256feEAB105`.
=> [R4R] fix: add ProxyOwnerUpgradeTime to mantle upgrade config

core/txpool/txpool.go, core/txpool/txpool_test.go
1. Fix the issue of repeated deduction of l1cost.
2. fix test cases to ensure `tx.GasPrice() < basefee.`
=> [R4R] fix: L1Cost subtracted repeatedly && test cast

cmd/geth/main.go, cmd/utils/flags.go, eth/api_backend.go, eth/backend.go, eth/ethconfig/config.go, eth/gasprice/feehistory_test.go, eth/gasprice/gasprice.go, eth/gasprice/gasprice_test.go, eth/gasprice/optimism-gasprice.go, eth/gasprice/optimism-gasprice_test.go, les/api_backend.go, les/client.go, miner/miner.go
**Description**
We have made some changes to `eth_maxPriorityFeePerGas` api that it returns a constant zero.
Revert it and use the same way to suggest as Optimism.
Reset `miner.gasprice` default value from `1gwei` to `0.001gwei`
**Tests**
```
=== RUN   TestFeeHistory
--- PASS: TestFeeHistory (0.12s)
=== RUN   TestSuggestTipCap
--- PASS: TestSuggestTipCap (0.04s)
=== RUN   TestSuggestOptimismPriorityFee
--- PASS: TestSuggestOptimismPriorityFee (0.00s)
PASS
ok      github.com/ethereum/go-ethereum/eth/gasprice    1.068s
```
**Additional context**
**Metadata**
=> eth/gasprice: use the same model as Op for priority fee suggestion
